### 马尔可夫平稳收敛验证

In [0]:
import numpy as np

In [5]:
transfer_matrix = np.array([[0.6,0.2,0.2],[0.3,0.4,0.3],[0,0.3,0.7]], dtype=np.float32)
start_matrix = np.array([[0.5, 0.2, 0.3]], dtype=np.float32)
for i in range(30):
    print(start_matrix)
    start_matrix = np.dot(start_matrix, transfer_matrix)

[[0.5 0.2 0.3]]
[[0.36 0.27 0.37]]
[[0.29700002 0.291      0.412     ]]
[[0.2655     0.29940003 0.43510002]]
[[0.24912003 0.30339003 0.44749004]]
[[0.24048904 0.305427   0.45408404]]
[[0.23592153 0.30649382 0.45758474]]
[[0.23350108 0.30705726 0.45944178]]
[[0.23221785 0.30735564 0.46042663]]
[[0.2315374  0.30751383 0.4609489 ]]
[[0.23117661 0.3075977  0.46122587]]
[[0.23098528 0.30764216 0.46137273]]
[[0.23088382 0.30766574 0.46145064]]
[[0.23083001 0.30767828 0.46149194]]
[[0.2308015  0.3076849  0.46151385]]
[[0.23078638 0.30768842 0.46152544]]
[[0.23077837 0.30769026 0.4615316 ]]
[[0.2307741  0.30769128 0.4615349 ]]
[[0.23077185 0.3076918  0.46153665]]
[[0.23077068 0.3076921  0.46153757]]
[[0.23077005 0.30769226 0.46153808]]
[[0.23076972 0.30769235 0.4615383 ]]
[[0.23076954 0.30769238 0.46153846]]
[[0.23076946 0.3076924  0.46153855]]
[[0.2307694  0.30769244 0.4615386 ]]
[[0.23076938 0.30769244 0.46153864]]
[[0.23076937 0.30769247 0.46153867]]
[[0.23076937 0.30769247 0.46153867]]
[[0

### 换一个初始矩阵试试

In [6]:
transfer_matrix = np.array([[0.6,0.2,0.2],[0.3,0.4,0.3],[0,0.3,0.7]], dtype=np.float32)
start_matrix = np.array([[0.3, 0.5, 0.2]], dtype=np.float32)
for i in range(50):
    print(start_matrix)
    start_matrix = np.dot(start_matrix, transfer_matrix)

[[0.3 0.5 0.2]]
[[0.33       0.32       0.35000002]]
[[0.29400003 0.29900002 0.407     ]]
[[0.26610005 0.30050004 0.43340003]]
[[0.24981005 0.30344003 0.44675004]]
[[0.24091806 0.30536306 0.45371908]]
[[0.23615977 0.3064446  0.45739588]]
[[0.23362926 0.30702856 0.45934242]]
[[0.23228613 0.30734003 0.46037412]]
[[0.23157369 0.3075055  0.4609211 ]]
[[0.23119587 0.3075933  0.46121114]]
[[0.23099552 0.30763984 0.46136495]]
[[0.23088928 0.30766454 0.46144652]]
[[0.23083293 0.30767763 0.4614898 ]]
[[0.23080306 0.3076846  0.4615127 ]]
[[0.23078722 0.3076883  0.4615249 ]]
[[0.23077883 0.30769026 0.46153137]]
[[0.23077437 0.30769128 0.4615348 ]]
[[0.23077202 0.3076918  0.4615366 ]]
[[0.23077077 0.3076921  0.46153754]]
[[0.23077011 0.30769226 0.46153808]]
[[0.23076975 0.30769235 0.46153834]]
[[0.23076957 0.3076924  0.4615385 ]]
[[0.23076949 0.30769244 0.46153855]]
[[0.23076943 0.30769247 0.4615386 ]]
[[0.23076941 0.30769247 0.46153867]]
[[0.2307694  0.30769247 0.46153867]]
[[0.2307694  0.3076924